<a href="https://colab.research.google.com/github/mzackyalqifahry/pemantauan-hidrologi-github/blob/main/M_ZACKY_ALQIFAHRY_TUGAS_TEORI_VEKTOR_DAN_MATRIKS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

def solve_robotics_problem():
    J = np.array([[2.0, 1.0, 0.0],
                  [1.0, 2.0, 1.0],
                  [0.0, 1.0, 2.0]])
    dx = np.array([5.0, 7.0, 5.0])

    n = len(J)

    print("\n=== Dekomposisi LU ===")
    L_doo = np.eye(n)
    U_doo = np.zeros((n, n))

    for i in range(n):
        # Upper Matrix
        for k in range(i, n):
            sum_val = sum(L_doo[i][j] * U_doo[j][k] for j in range(i))
            U_doo[i][k] = J[i][k] - sum_val
        # Lower Matrix
        for k in range(i, n):
            if i == k:
                L_doo[i][i] = 1
            else:
                sum_val = sum(L_doo[k][j] * U_doo[j][i] for j in range(i))
                L_doo[k][i] = (J[k][i] - sum_val) / U_doo[i][i]

    print("Matriks L:\n", L_doo)
    print("Matriks U:\n", U_doo)

    y = np.zeros(n)
    for i in range(n):
        y[i] = (dx[i] - sum(L_doo[i][j] * y[j] for j in range(i))) / L_doo[i][i]

    dq_doo = np.zeros(n)
    for i in range(n-1, -1, -1):
        dq_doo[i] = (y[i] - sum(U_doo[i][j] * dq_doo[j] for j in range(i+1, n))) / U_doo[i][i]

    print("Hasil Metode (Dekomposisi LU):", dq_doo)


    # Metode Crout
    print("\n=== METODE CROUT ===")
    L_crout = np.zeros((n, n))
    U_crout = np.eye(n)

    for j in range(n):
        # Lower Matrix
        for i in range(j, n):
            sum_val = sum(L_crout[i][k] * U_crout[k][j] for k in range(j))
            L_crout[i][j] = J[i][j] - sum_val
        # Upper Matrix
        for i in range(j, n):
            if i == j: continue
            sum_val = sum(L_crout[j][k] * U_crout[k][i] for k in range(j))
            U_crout[j][i] = (J[j][i] - sum_val) / L_crout[j][j]

    print("Matriks L:\n", L_crout)
    print("Matriks U:\n", U_crout)

    y_crout = np.zeros(n)
    for i in range(n):
        y_crout[i] = (dx[i] - sum(L_crout[i][j] * y_crout[j] for j in range(i))) / L_crout[i][i]

    dq_crout = np.zeros(n)
    for i in range(n-1, -1, -1):
        dq_crout[i] = (y_crout[i] - sum(U_crout[i][j] * dq_crout[j] for j in range(i+1, n))) / U_crout[i][i]

    print("Hasil Metode (Crout):", dq_crout)

solve_robotics_problem()


=== Dekomposisi LU ===
Matriks L:
 [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.         0.66666667 1.        ]]
Matriks U:
 [[2.         1.         0.        ]
 [0.         1.5        1.        ]
 [0.         0.         1.33333333]]
Hasil Metode (Dekomposisi LU): [1.5 2.  1.5]

=== METODE CROUT ===
Matriks L:
 [[2.         0.         0.        ]
 [1.         1.5        0.        ]
 [0.         1.         1.33333333]]
Matriks U:
 [[1.         0.5        0.        ]
 [0.         1.         0.66666667]
 [0.         0.         1.        ]]
Hasil Metode (Crout): [1.5 2.  1.5]
